import { db } from "@biume/db";
import {
  advancedReport,
  appointments,
  audioCapture,
} from "@biume/db/schema/index";
import { and, eq, inArray } from "drizzle-orm";
import type { CaptureRepository } from "./capture.service";

/**
 * Every statement below filters on `organizationId` as well as `id`. A capture
 * identifier is generated by a client, so it is never sufficient on its own to
 * authorize a read or a write.
 */
export function createCaptureRepository(): CaptureRepository {
  return {
    async findCapture({ id, organizationId }) {
      const [row] = await db
        .select()
        .from(audioCapture)
        .where(
          and(
            eq(audioCapture.id, id),
            eq(audioCapture.organizationId, organizationId),
          ),
        )
        .limit(1);
      return row ?? null;
    },

    async insertCapture(row) {
      // A concurrent device may already hold this primary key. `onConflictDoNothing`
      // returns no row, which the service treats as "reread and compare".
      const [inserted] = await db
        .insert(audioCapture)
        .values(row)
        .onConflictDoNothing({ target: audioCapture.id })
        .returning();
      return inserted ?? null;
    },

    async findAppointmentContext({ appointmentId, organizationId }) {
      const [row] = await db
        .select({
          patientId: appointments.patientId,
          reportId: advancedReport.id,
        })
        .from(appointments)
        .leftJoin(
          advancedReport,
          eq(advancedReport.appointmentId, appointments.id),
        )
        .where(
          and(
            eq(appointments.id, appointmentId),
            eq(appointments.organizationId, organizationId),
          ),
        )
        .limit(1);
      if (!row) return null;
      return { patientId: row.patientId, reportId: row.reportId };
    },

    async transitionCapture({ id, organizationId, from, to, patch }) {
      const [updated] = await db
        .update(audioCapture)
        .set({ ...patch, status: to })
        .where(
          and(
            eq(audioCapture.id, id),
            eq(audioCapture.organizationId, organizationId),
            inArray(audioCapture.status, [...from]),
          ),
        )
        .returning();
      return updated ?? null;
    },
  };
}
