// AUTO-GENERATED by atmn pull
// DO NOT EDIT MANUALLY

declare module "@useautumn/sdk" {
  // Features
  export const suivi_de_sant_intelligent: Feature;
  export const rapports_illimits: Feature;
  export const ia_vulgarisation: Feature;
  export const export_pdf_professionnel: Feature;
  export const fiches_clients_patients_illimits: Feature;
  export const support_prioritaire: Feature;

  // Plans
  export const all_inclusive_monthly: Plan;
  export const all_inclusive_yearly: Plan;

  // Base types
  export type Feature = import("./autumn.config").Feature;
  export type Plan = import("./autumn.config").Plan;
}
