/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as SelectOrganizationRouteImport } from './routes/select-organization'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CreateOrganizationRouteImport } from './routes/create-organization'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardReportsRouteImport } from './routes/dashboard/reports'
import { Route as DashboardPatientsRouteImport } from './routes/dashboard/patients'
import { Route as DashboardOwnersRouteImport } from './routes/dashboard/owners'
import { Route as DashboardClientsRouteImport } from './routes/dashboard/clients'
import { Route as DashboardAgendaRouteImport } from './routes/dashboard/agenda'
import { Route as ApiUploadthingRouteImport } from './routes/api/uploadthing'
import { Route as DashboardReportsIdRouteImport } from './routes/dashboard/reports_.$id'
import { Route as ApiAutumnSplatRouteImport } from './routes/api/autumn/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as DashboardReportsIdEditRouteImport } from './routes/dashboard/reports_.$id.edit'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const SelectOrganizationRoute = SelectOrganizationRouteImport.update({
  id: '/select-organization',
  path: '/select-organization',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateOrganizationRoute = CreateOrganizationRouteImport.update({
  id: '/create-organization',
  path: '/create-organization',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReportsRoute = DashboardReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPatientsRoute = DashboardPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOwnersRoute = DashboardOwnersRouteImport.update({
  id: '/owners',
  path: '/owners',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardClientsRoute = DashboardClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAgendaRoute = DashboardAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiUploadthingRoute = ApiUploadthingRouteImport.update({
  id: '/api/uploadthing',
  path: '/api/uploadthing',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardReportsIdRoute = DashboardReportsIdRouteImport.update({
  id: '/reports_/$id',
  path: '/reports/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiAutumnSplatRoute = ApiAutumnSplatRouteImport.update({
  id: '/api/autumn/$',
  path: '/api/autumn/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardReportsIdEditRoute = DashboardReportsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => DashboardReportsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create-organization': typeof CreateOrganizationRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/select-organization': typeof SelectOrganizationRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/api/uploadthing': typeof ApiUploadthingRoute
  '/dashboard/agenda': typeof DashboardAgendaRoute
  '/dashboard/clients': typeof DashboardClientsRoute
  '/dashboard/owners': typeof DashboardOwnersRoute
  '/dashboard/patients': typeof DashboardPatientsRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/autumn/$': typeof ApiAutumnSplatRoute
  '/dashboard/reports/$id': typeof DashboardReportsIdRouteWithChildren
  '/dashboard/reports/$id/edit': typeof DashboardReportsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create-organization': typeof CreateOrganizationRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/select-organization': typeof SelectOrganizationRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/api/uploadthing': typeof ApiUploadthingRoute
  '/dashboard/agenda': typeof DashboardAgendaRoute
  '/dashboard/clients': typeof DashboardClientsRoute
  '/dashboard/owners': typeof DashboardOwnersRoute
  '/dashboard/patients': typeof DashboardPatientsRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/autumn/$': typeof ApiAutumnSplatRoute
  '/dashboard/reports/$id': typeof DashboardReportsIdRouteWithChildren
  '/dashboard/reports/$id/edit': typeof DashboardReportsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create-organization': typeof CreateOrganizationRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/select-organization': typeof SelectOrganizationRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/api/uploadthing': typeof ApiUploadthingRoute
  '/dashboard/agenda': typeof DashboardAgendaRoute
  '/dashboard/clients': typeof DashboardClientsRoute
  '/dashboard/owners': typeof DashboardOwnersRoute
  '/dashboard/patients': typeof DashboardPatientsRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/autumn/$': typeof ApiAutumnSplatRoute
  '/dashboard/reports_/$id': typeof DashboardReportsIdRouteWithChildren
  '/dashboard/reports_/$id/edit': typeof DashboardReportsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create-organization'
    | '/dashboard'
    | '/forgot-password'
    | '/reset-password'
    | '/select-organization'
    | '/signin'
    | '/signup'
    | '/api/uploadthing'
    | '/dashboard/agenda'
    | '/dashboard/clients'
    | '/dashboard/owners'
    | '/dashboard/patients'
    | '/dashboard/reports'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/api/auth/$'
    | '/api/autumn/$'
    | '/dashboard/reports/$id'
    | '/dashboard/reports/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create-organization'
    | '/forgot-password'
    | '/reset-password'
    | '/select-organization'
    | '/signin'
    | '/signup'
    | '/api/uploadthing'
    | '/dashboard/agenda'
    | '/dashboard/clients'
    | '/dashboard/owners'
    | '/dashboard/patients'
    | '/dashboard/reports'
    | '/dashboard/settings'
    | '/dashboard'
    | '/api/auth/$'
    | '/api/autumn/$'
    | '/dashboard/reports/$id'
    | '/dashboard/reports/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/create-organization'
    | '/dashboard'
    | '/forgot-password'
    | '/reset-password'
    | '/select-organization'
    | '/signin'
    | '/signup'
    | '/api/uploadthing'
    | '/dashboard/agenda'
    | '/dashboard/clients'
    | '/dashboard/owners'
    | '/dashboard/patients'
    | '/dashboard/reports'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/api/auth/$'
    | '/api/autumn/$'
    | '/dashboard/reports_/$id'
    | '/dashboard/reports_/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateOrganizationRoute: typeof CreateOrganizationRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SelectOrganizationRoute: typeof SelectOrganizationRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  ApiUploadthingRoute: typeof ApiUploadthingRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiAutumnSplatRoute: typeof ApiAutumnSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/select-organization': {
      id: '/select-organization'
      path: '/select-organization'
      fullPath: '/select-organization'
      preLoaderRoute: typeof SelectOrganizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-organization': {
      id: '/create-organization'
      path: '/create-organization'
      fullPath: '/create-organization'
      preLoaderRoute: typeof CreateOrganizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/reports': {
      id: '/dashboard/reports'
      path: '/reports'
      fullPath: '/dashboard/reports'
      preLoaderRoute: typeof DashboardReportsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/patients': {
      id: '/dashboard/patients'
      path: '/patients'
      fullPath: '/dashboard/patients'
      preLoaderRoute: typeof DashboardPatientsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/owners': {
      id: '/dashboard/owners'
      path: '/owners'
      fullPath: '/dashboard/owners'
      preLoaderRoute: typeof DashboardOwnersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/clients': {
      id: '/dashboard/clients'
      path: '/clients'
      fullPath: '/dashboard/clients'
      preLoaderRoute: typeof DashboardClientsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/agenda': {
      id: '/dashboard/agenda'
      path: '/agenda'
      fullPath: '/dashboard/agenda'
      preLoaderRoute: typeof DashboardAgendaRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/uploadthing': {
      id: '/api/uploadthing'
      path: '/api/uploadthing'
      fullPath: '/api/uploadthing'
      preLoaderRoute: typeof ApiUploadthingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/reports_/$id': {
      id: '/dashboard/reports_/$id'
      path: '/reports/$id'
      fullPath: '/dashboard/reports/$id'
      preLoaderRoute: typeof DashboardReportsIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/autumn/$': {
      id: '/api/autumn/$'
      path: '/api/autumn/$'
      fullPath: '/api/autumn/$'
      preLoaderRoute: typeof ApiAutumnSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/reports_/$id/edit': {
      id: '/dashboard/reports_/$id/edit'
      path: '/edit'
      fullPath: '/dashboard/reports/$id/edit'
      preLoaderRoute: typeof DashboardReportsIdEditRouteImport
      parentRoute: typeof DashboardReportsIdRoute
    }
  }
}

interface DashboardReportsIdRouteChildren {
  DashboardReportsIdEditRoute: typeof DashboardReportsIdEditRoute
}

const DashboardReportsIdRouteChildren: DashboardReportsIdRouteChildren = {
  DashboardReportsIdEditRoute: DashboardReportsIdEditRoute,
}

const DashboardReportsIdRouteWithChildren =
  DashboardReportsIdRoute._addFileChildren(DashboardReportsIdRouteChildren)

interface DashboardRouteChildren {
  DashboardAgendaRoute: typeof DashboardAgendaRoute
  DashboardClientsRoute: typeof DashboardClientsRoute
  DashboardOwnersRoute: typeof DashboardOwnersRoute
  DashboardPatientsRoute: typeof DashboardPatientsRoute
  DashboardReportsRoute: typeof DashboardReportsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardReportsIdRoute: typeof DashboardReportsIdRouteWithChildren
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAgendaRoute: DashboardAgendaRoute,
  DashboardClientsRoute: DashboardClientsRoute,
  DashboardOwnersRoute: DashboardOwnersRoute,
  DashboardPatientsRoute: DashboardPatientsRoute,
  DashboardReportsRoute: DashboardReportsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardReportsIdRoute: DashboardReportsIdRouteWithChildren,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateOrganizationRoute: CreateOrganizationRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SelectOrganizationRoute: SelectOrganizationRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  ApiUploadthingRoute: ApiUploadthingRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiAutumnSplatRoute: ApiAutumnSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
