/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardReportsRouteImport } from './routes/_dashboard/reports'
import { Route as DashboardOwnersRouteImport } from './routes/_dashboard/owners'
import { Route as DashboardAgendaRouteImport } from './routes/_dashboard/agenda'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as DashboardReportsIdRouteImport } from './routes/_dashboard/reports_.$id'
import { Route as DashboardReportsIdEditRouteImport } from './routes/_dashboard/reports_.$id.edit'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardReportsRoute = DashboardReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOwnersRoute = DashboardOwnersRouteImport.update({
  id: '/owners',
  path: '/owners',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAgendaRoute = DashboardAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardReportsIdRoute = DashboardReportsIdRouteImport.update({
  id: '/reports_/$id',
  path: '/reports/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReportsIdEditRoute = DashboardReportsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => DashboardReportsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/agenda': typeof DashboardAgendaRoute
  '/owners': typeof DashboardOwnersRoute
  '/reports': typeof DashboardReportsRoute
  '/reports/$id': typeof DashboardReportsIdRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/reports/$id/edit': typeof DashboardReportsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/agenda': typeof DashboardAgendaRoute
  '/owners': typeof DashboardOwnersRoute
  '/reports': typeof DashboardReportsRoute
  '/reports/$id': typeof DashboardReportsIdRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/reports/$id/edit': typeof DashboardReportsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_dashboard': typeof DashboardRouteWithChildren
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/_dashboard/agenda': typeof DashboardAgendaRoute
  '/_dashboard/owners': typeof DashboardOwnersRoute
  '/_dashboard/reports': typeof DashboardReportsRoute
  '/_dashboard/reports_/$id': typeof DashboardReportsIdRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_dashboard/reports_/$id/edit': typeof DashboardReportsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/signin'
    | '/signup'
    | '/agenda'
    | '/owners'
    | '/reports'
    | '/reports/$id'
    | '/api/auth/$'
    | '/reports/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/signin'
    | '/signup'
    | '/agenda'
    | '/owners'
    | '/reports'
    | '/reports/$id'
    | '/api/auth/$'
    | '/reports/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/_dashboard'
    | '/signin'
    | '/signup'
    | '/_dashboard/agenda'
    | '/_dashboard/owners'
    | '/_dashboard/reports'
    | '/_dashboard/reports_/$id'
    | '/api/auth/$'
    | '/_dashboard/reports_/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/reports': {
      id: '/_dashboard/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof DashboardReportsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/owners': {
      id: '/_dashboard/owners'
      path: '/owners'
      fullPath: '/owners'
      preLoaderRoute: typeof DashboardOwnersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/agenda': {
      id: '/_dashboard/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof DashboardAgendaRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/reports_/$id': {
      id: '/_dashboard/reports_/$id'
      path: '/reports/$id'
      fullPath: '/reports/$id'
      preLoaderRoute: typeof DashboardReportsIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/reports_/$id/edit': {
      id: '/_dashboard/reports_/$id/edit'
      path: '/edit'
      fullPath: '/reports/$id/edit'
      preLoaderRoute: typeof DashboardReportsIdEditRouteImport
      parentRoute: typeof DashboardReportsIdRoute
    }
  }
}

interface DashboardReportsIdRouteChildren {
  DashboardReportsIdEditRoute: typeof DashboardReportsIdEditRoute
}

const DashboardReportsIdRouteChildren: DashboardReportsIdRouteChildren = {
  DashboardReportsIdEditRoute: DashboardReportsIdEditRoute,
}

const DashboardReportsIdRouteWithChildren =
  DashboardReportsIdRoute._addFileChildren(DashboardReportsIdRouteChildren)

interface DashboardRouteChildren {
  DashboardAgendaRoute: typeof DashboardAgendaRoute
  DashboardOwnersRoute: typeof DashboardOwnersRoute
  DashboardReportsRoute: typeof DashboardReportsRoute
  DashboardReportsIdRoute: typeof DashboardReportsIdRouteWithChildren
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAgendaRoute: DashboardAgendaRoute,
  DashboardOwnersRoute: DashboardOwnersRoute,
  DashboardReportsRoute: DashboardReportsRoute,
  DashboardReportsIdRoute: DashboardReportsIdRouteWithChildren,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
