/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DashboardReportsRouteImport } from './routes/dashboard/reports'
import { Route as DashboardOwnersRouteImport } from './routes/dashboard/owners'
import { Route as DashboardAgendaRouteImport } from './routes/dashboard/agenda'
import { Route as DashboardReportsIdRouteImport } from './routes/dashboard/reports_.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as DashboardReportsIdEditRouteImport } from './routes/dashboard/reports_.$id.edit'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardReportsRoute = DashboardReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOwnersRoute = DashboardOwnersRouteImport.update({
  id: '/owners',
  path: '/owners',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAgendaRoute = DashboardAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReportsIdRoute = DashboardReportsIdRouteImport.update({
  id: '/reports_/$id',
  path: '/reports/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardReportsIdEditRoute = DashboardReportsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => DashboardReportsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/dashboard/agenda': typeof DashboardAgendaRoute
  '/dashboard/owners': typeof DashboardOwnersRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/reports/$id': typeof DashboardReportsIdRouteWithChildren
  '/dashboard/reports/$id/edit': typeof DashboardReportsIdEditRoute
}
export interface FileRoutesByTo {
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/dashboard/agenda': typeof DashboardAgendaRoute
  '/dashboard/owners': typeof DashboardOwnersRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/reports/$id': typeof DashboardReportsIdRouteWithChildren
  '/dashboard/reports/$id/edit': typeof DashboardReportsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/dashboard/agenda': typeof DashboardAgendaRoute
  '/dashboard/owners': typeof DashboardOwnersRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/reports_/$id': typeof DashboardReportsIdRouteWithChildren
  '/dashboard/reports_/$id/edit': typeof DashboardReportsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/dashboard'
    | '/forgot-password'
    | '/reset-password'
    | '/signin'
    | '/signup'
    | '/dashboard/agenda'
    | '/dashboard/owners'
    | '/dashboard/reports'
    | '/api/auth/$'
    | '/dashboard/reports/$id'
    | '/dashboard/reports/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/dashboard'
    | '/forgot-password'
    | '/reset-password'
    | '/signin'
    | '/signup'
    | '/dashboard/agenda'
    | '/dashboard/owners'
    | '/dashboard/reports'
    | '/api/auth/$'
    | '/dashboard/reports/$id'
    | '/dashboard/reports/$id/edit'
  id:
    | '__root__'
    | '/dashboard'
    | '/forgot-password'
    | '/reset-password'
    | '/signin'
    | '/signup'
    | '/dashboard/agenda'
    | '/dashboard/owners'
    | '/dashboard/reports'
    | '/api/auth/$'
    | '/dashboard/reports_/$id'
    | '/dashboard/reports_/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRoute: typeof DashboardRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/reports': {
      id: '/dashboard/reports'
      path: '/reports'
      fullPath: '/dashboard/reports'
      preLoaderRoute: typeof DashboardReportsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/owners': {
      id: '/dashboard/owners'
      path: '/owners'
      fullPath: '/dashboard/owners'
      preLoaderRoute: typeof DashboardOwnersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/agenda': {
      id: '/dashboard/agenda'
      path: '/agenda'
      fullPath: '/dashboard/agenda'
      preLoaderRoute: typeof DashboardAgendaRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/reports_/$id': {
      id: '/dashboard/reports_/$id'
      path: '/reports/$id'
      fullPath: '/dashboard/reports/$id'
      preLoaderRoute: typeof DashboardReportsIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/reports_/$id/edit': {
      id: '/dashboard/reports_/$id/edit'
      path: '/edit'
      fullPath: '/dashboard/reports/$id/edit'
      preLoaderRoute: typeof DashboardReportsIdEditRouteImport
      parentRoute: typeof DashboardReportsIdRoute
    }
  }
}

interface DashboardReportsIdRouteChildren {
  DashboardReportsIdEditRoute: typeof DashboardReportsIdEditRoute
}

const DashboardReportsIdRouteChildren: DashboardReportsIdRouteChildren = {
  DashboardReportsIdEditRoute: DashboardReportsIdEditRoute,
}

const DashboardReportsIdRouteWithChildren =
  DashboardReportsIdRoute._addFileChildren(DashboardReportsIdRouteChildren)

interface DashboardRouteChildren {
  DashboardAgendaRoute: typeof DashboardAgendaRoute
  DashboardOwnersRoute: typeof DashboardOwnersRoute
  DashboardReportsRoute: typeof DashboardReportsRoute
  DashboardReportsIdRoute: typeof DashboardReportsIdRouteWithChildren
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAgendaRoute: DashboardAgendaRoute,
  DashboardOwnersRoute: DashboardOwnersRoute,
  DashboardReportsRoute: DashboardReportsRoute,
  DashboardReportsIdRoute: DashboardReportsIdRouteWithChildren,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DashboardRoute: DashboardRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
